import type { Metadata } from "next";
import "./globals.css";
import { Geist, Playfair } from 'next/font/google'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-geist',
})

const playfair = Playfair({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-play',
})



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased ${geist.variable} ${playfair.variable}`}
      >

        {children}
      </body>
    </html>
  );
}
